import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import HeadBar from "@/components/main/Header/HeadBar";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import AuthProvider from "./AuthProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <AuthProvider session={session}>
        <body className={
          cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )
        }>

          <div className="flex flex-col h-screen">
            <div><HeadBar /></div>
            <div className="flex-1">{children}</div>
          </div>

        </body>
      </AuthProvider>
    </html>
  );
}
