# docker-compose.yml

version: '3.9'
services:

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=stormforgeadmin
      - POSTGRES_PASSWORD=stormforgeadminpassword
      - POSTGRES_DB=stormforgedb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
